access_key_id = "<AWS_ACCESS_KEY_ID>"
secret_access_key = "<AWS_SECRET_ACCESS_KEY>"
session_token = "<AWS_SESSION_TOKEN>"
region = "<AWS_REGION_NAME>"
warehouse = "<WAREHOUSE_PATH>"
namespace = "<NAMESPACE>"
table = "<TABLE>"
